name: ambulance_attendance

description: نظام الإسعاف المركزي

publish_to: "none"

version: 1.0.0+1

environment:
sdk: ">=3.0.0 <4.0.0"

dependencies:
flutter:
sdk: flutter

cupertino_icons: ^1.0.6

Supabase

supabase_flutter: ^2.17.2

QR Scanner

flutter_zxing: ^2.2.0

QR Code Generator

qr_flutter: ^4.1.0

Maps

flutter_map: ^6.1.0
latlong2: ^0.9.1

Location / GPS

geolocator: ^10.1.0

Open external links

url_launcher: ^6.3.0

dev_dependencies:
flutter_test:
sdk: flutter

flutter_lints: ^3.0.0

App Icon

flutter_launcher_icons: ^0.13.1

Splash Screen

flutter_native_splash: ^2.4.0

flutter:
uses-material-design: true

assets:
- assets/images/

flutter_launcher_icons:
android: true
ios: false
image_path: "app_icon.png"

flutter_native_splash:
color: "#FFFFFF"
image: "splash.png"
android: true
ios: false
fullscreen: true
