name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'
          channel: 'stable'

      - name: Create missing platform folders with Camera Permission
        run: |
          flutter create --project-name ambulance_app --org com.ambulance .
          sed -i 's/android:label="ambulance_app"/android:label="الإسعاف المركزي"/' android/app/src/main/AndroidManifest.xml
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.CAMERA"\/>' android/app/src/main/AndroidManifest.xml

      - run: flutter pub get
      - run: dart run flutter_launcher_icons
      - run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
